services:
  - type: web
    name: tododo
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn tododo.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: your_secret_key
      - key: DEBUG
        value: 'False'
    staticPublishPath: staticfiles
    routes:
      - type: rewrite
        source: /static/(.*)
        destination: /static/$1
      - type: rewrite
        source: /media/(.*)
        destination: /media/$1