# Generated by Django 5.0.6 on 2024-07-17 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_info', models.CharField(max_length=50)),
                ('what_info', models.CharField(max_length=50)),
                ('type_info', models.CharField(choices=[('billings', 'Billings'), ('earnings', 'Earnings')], default='billings', max_length=20)),
                ('important_info', models.BooleanField(default=False, verbose_name='Is this important ?')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('money_info', models.FloatField(verbose_name='Money')),
            ],
        ),
        migrations.CreateModel(
            name='TitleTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=20)),
                ('important', models.BooleanField(default=False, verbose_name='Is it important ?')),
                ('active', models.BooleanField(default=True, verbose_name='Is it active?')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.titletodo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
