# Generated by Django 5.0.6 on 2024-08-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='born',
            field=models.DateTimeField(null=True),
        ),
    ]
