# Generated by Django 5.0.6 on 2024-07-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_created_at_todolist_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='active',
            field=models.BooleanField(default=True, verbose_name="Mark if it's uncompleted"),
        ),
    ]
